# Generated by Django 4.1.4 on 2022-12-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileforms',
            old_name='arquivo',
            new_name='arquivo_especificacao',
        ),
    ]
